---
# file: xastir/main.yml
- name: xastir
  hosts: localhost
  connection: localhost
  tasks:
    - name: install or update to the latest version of xastir
      ansible.builtin.set_fact:
        xastir_install: "{{ 'true' }}"
    - name: debug xastir_install
      ansible.builtin.debug: msg="{{ xastir_install }}"
    - name: install xastir dependencies
      become: true
      ansible.builtin.apt:
        pkg:
          - autoconf
          - automake
          - build-essential
          - extra-xdg-menus
          - festival
          - festival-dev
          - git
          - gpsman
          - gpsmanshp
          - graphicsmagick
          - gv
          - libax25-dev
          - libcurl4-openssl-dev
          - libdb5.3-dev
          - libgeotiff-dev
          - libgraphicsmagick1-dev
          - libmotif-dev
          - libpcre3-dev
          - libproj-dev
          - libshp-dev
          - libwebp-dev
          - python3-dev
          - shapelib
          - xfonts-100dpi
          - xfonts-75dpi
          - xorg-dev
        update_cache: true
        cache_valid_time: 3600
    - name: set fonts
      ansible.builtin.command: 'xset +fp /usr/share/fonts/X11/100dpi,/usr/share/fonts/X11/75dpi'
      when: xastir_install
    - name: clone xastir repo
      ansible.builtin.git:
        repo: 'https://www.github.com/Xastir/Xastir.git'
        dest: "{{ ansible_env.HOME }}/Downloads/Xastir"
        version: master
    - name: bootstrap xastir
      ansible.builtin.command: 'bash {{ item }} chdir={{ ansible_env.HOME }}/Downloads/Xastir/'
      with_items:
        - ./bootstrap.sh
      when: xastir_install
    - name: build folder
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/Downloads/Xastir/build"
        state: directory
        mode: 0755
    - name: configure xastir
      ansible.builtin.command: '{{ item }} chdir={{ ansible_env.HOME }}/Downloads/Xastir/build'
      with_items:
        - ../configure CPPFLAGS="-I/usr/include/geotiff"
      when: xastir_install
    - name: make
      ansible.builtin.command: '{{ item }} chdir={{ ansible_env.HOME }}//Downloads/Xastir/build'
      with_items:
        - make -j{{ ansible_facts['processor_count'] }}
      when: xastir_install
    - name: make install
      become: true
      ansible.builtin.command: '{{ item }} chdir={{ ansible_env.HOME }}//Downloads/Xastir/build'
      with_items:
        - make install
      when: xastir_install
