---
# file: js8call/main.yml
- name: Js8call
  hosts: localhost
  connection: localhost
  tasks:
    - name: Get installed js8call version # noqa risky-shell-pipe
      ansible.builtin.shell: |
        if hash js8call 2>/dev/null; then
            apt-cache policy js8call | awk  'FNR == 2 {print $2}'
        else echo "NOT INSTALLED"
        fi
      register: js8call_version
      changed_when: false
    - name: Set js8call installed version
      ansible.builtin.set_fact:
        js8call: "{{ js8call_version.stdout }}"

    - name: Latest js8call version check # noqa risky-shell-pipe
      ansible.builtin.shell: |
        curl -s http://files.js8call.com/latest.html | grep "<strong>" |
        grep -o [0-9].[0-9]
      register: js8call_online
      changed_when: false
    - name: Set latest js8call version
      ansible.builtin.set_fact:
        newjs8call: "{{ js8call_online.stdout }}"

    - name: Get js8call download link # noqa risky-shell-pipe
      ansible.builtin.shell: |
        curl -s http://files.js8call.com/latest.html |
        grep -o "http://files.js8call.com/[0-9].[0-9].[0-9]/js8call_[0-9].[0-9].[0-9]_armhf.deb" | head -n 1
      register: js8call_download
      changed_when: false
    - name: Set installed js8call version
      ansible.builtin.set_fact:
        js8call_url: "{{ js8call_download.stdout }}"

    - name: Install js8call if not installed
      ansible.builtin.set_fact:
        js8call_install: "{{ 'true' if (js8call != js8call_online) else 'false' }}"
    - name: Debug js8call_install
      ansible.builtin.debug:
        msg: "{{ js8call_install }}"

    - name: Install js8call dependencies
      become: true
      ansible.builtin.apt:
        pkg:
          - extra-xdg-menus
          - gfortran
          - libqt5multimedia5
          - libqt5multimedia5-plugins
          - libqt5multimediawidgets5
          - libqt5serialport5
        update_cache: true
        cache_valid_time: 3600
      when: js8call_install

    - name: Download js8call deb file and install
      become: true
      ansible.builtin.apt:
        deb: "{{ js8call_url }}"
      when: js8call_install

    - name: Install js8call desktop icon
      ansible.builtin.copy:
        src: js8call.desktop
        dest: "{{ ansible_env.HOME }}/Desktop/js8call.desktop"
        mode: "0644"
      when: js8call_install
