---
# file: flamp/main.yml
- name: Flamp
  hosts: localhost
  connection: localhost
  tasks:
    - name: Get installed flamp version # noqa risky-shell-pipe
      ansible.builtin.shell: |
        if hash flamp 2>/dev/null; then
            flamp --version | awk 'FNR == 1 {print $2}'
        else
            echo "NOT INSTALLED"
        fi
      register: flamp_version
      changed_when: false
    - name: Debug installed flamp version
      ansible.builtin.set_fact:
        flamp: "{{ flamp_version.stdout }}"
    - name: Check latest flamp version from sourceforge # noqa risky-shell-pipe
      ansible.builtin.shell: |
        curl -s https://sourceforge.net/projects/fldigi/files/flamp/ | grep .tar.gz | head -1 | awk -F "-" '{print $2}' | awk -F ".tar.gz" '{print $1}'
      register: flamp_online
      changed_when: false
    - name: Set flamp latest version
      ansible.builtin.set_fact:
        newflamp: "{{ flamp_online.stdout }}"
    - name: Install or update to the latest version of flamp
      ansible.builtin.set_fact:
        flamp_install: "{{ 'true' if (flamp != newflamp) else 'false' }}"
    - name: Debug flamp_install
      ansible.builtin.debug:
        msg: "{{ flamp_install }}"
    - name: Download flamp and extract
      ansible.builtin.unarchive:
        src: https://sourceforge.net/projects/fldigi/files/flamp/flamp-{{ newflamp }}.tar.gz
        dest: "{{ ansible_env.HOME }}/Downloads/"
        remote_src: true
        creates: "{{ ansible_env.HOME }}/Downloads/flamp-{{ newflamp }}"
      when: flamp_install

    - name: ./configure flamp
      ansible.builtin.command:
      args:
        chdir: "{{ ansible_env.HOME }}/Downloads/flamp-{{ newflamp }}"
        cmd: ./configure
        creates: "{{ ansible_env.HOME }}/Downloads/flamp-{{ newflamp }}/config.status"
      when: flamp_install

    - name: Make flamp
      ansible.builtin.command:
      args:
        chdir: "{{ ansible_env.HOME }}/Downloads/flamp-{{ newflamp }}"
        cmd: make -j{{ ansible_facts['processor_count'] }}
        creates: "{{ ansible_env.HOME }}/Downloads/flamp-{{ newflamp }}/src/flamp"
      when: flamp_install

    - name: Install flamp
      become: true
      ansible.builtin.command:
      args:
        chdir: "{{ ansible_env.HOME }}/Downloads/flamp-{{ newflamp }}"
        cmd: make install
        creates: /usr/local/bin/flamp
      when: flamp_install

    - name: Install flamp desktop icon
      ansible.builtin.copy:
        src: flamp.desktop
        dest: "{{ ansible_env.HOME }}/Desktop/flamp.desktop"
        mode: "0644"
      when: flamp_install
