---
# file: flwrap/main.yml
- name: Flwrap
  hosts: localhost
  connection: localhost
  tasks:
    - name: get installed flwrap version # noqa risky-shell-pipe
      ansible.builtin.shell: |
        if hash flwrap 2>/dev/null; then
            flwrap --version | awk 'FNR == 1 {print $2}'
        else
            echo "NOT INSTALLED"
        fi
      register: flwrap_version
      changed_when: false
    - name: Set flrwap installed version
      ansible.builtin.set_fact: flwrap="{{ flwrap_version.stdout }}"

    - name: Check latest flwrap version from sourceforge # noqa risky-shell-pipe
      ansible.builtin.shell: |
        curl -s https://sourceforge.net/projects/fldigi/files/flwrap/ | grep .tar.gz | head -1 | awk -F "-" '{print $2}' | awk -F ".tar.gz" '{print $1}'
      register: flwrap_online
      changed_when: false
    - name: Set flwrap latest version
      ansible.builtin.set_fact: newflwrap="{{  flwrap_online.stdout  }}"

    - name: Install or update to the latest version of flwrap
      ansible.builtin.set_fact:
        flwrap_install: "{{ 'true' if ( flwrap != newflwrap ) else 'false' }}"
    - name: Debug flwrap_install
      ansible.builtin.debug: msg="{{ flwrap_install }}"

    - name: Download flwrap and extract
      ansible.builtin.unarchive:
        src: https://sourceforge.net/projects/fldigi/files/flwrap/flwrap-{{ newflwrap }}.tar.gz
        dest: "{{ ansible_env.HOME }}/Downloads/"
        remote_src: true
        creates: "{{ ansible_env.HOME }}/Downloads/flwrap-{{ newflwrap }}"
      when: flwrap_install

    - name: ./configure flwrap
      ansible.builtin.command: '{{ item }} chdir={{ ansible_env.HOME }}/Downloads/flwrap-{{ newflwrap }}'
      with_items:
        - ./configure
      when: flwrap_install

    - name: Make flwrap
      ansible.builtin.command: '{{ item }} chdir={{ ansible_env.HOME }}/Downloads/flwrap-{{ newflwrap }}'
      with_items:
        - make -j{{ ansible_facts['processor_count'] }}
      when: flwrap_install

    - name: Install flwrap
      become: true
      ansible.builtin.command: '{{ item }} chdir={{ ansible_env.HOME }}/Downloads/flwrap-{{ newflwrap }}'
      with_items:
        - make install
      when: flwrap_install

    - name: Install flwrap desktop icon
      ansible.builtin.copy:
        src: flwrap.desktop
        dest: "{{ ansible_env.HOME }}/Desktop/flwrap.desktop"
        mode: "0644"
      when: flwrap_install
