---
# file: flwrap/main.yml
- name: flwrap
  hosts: localhost
  connection: localhost
  tasks:
    - name: get installed flwrap version
      shell: |
        if hash flwrap 2>/dev/null; then
            flwrap --version | awk 'FNR == 1 {print $2}'
        else
            echo "NOT INSTALLED"
        fi
      register: flwrap_version 
      changed_when: false
    - set_fact: flwrap="{{ flwrap_version.stdout }}"

    - name: check latest flwrap version from sourceforge
      shell: curl -s https://sourceforge.net/projects/fldigi/files/flwrap/ | grep .tar.gz | head -1 | awk -F "-" '{print $2}' | awk -F ".tar.gz" '{print $1}'
      register: flwrap_online
      args:
        warn: no
      changed_when: false
    - set_fact: newflwrap="{{  flwrap_online.stdout  }}"

    - name: install or update to the latest version of flwrap
      set_fact:
        flwrap_install: "{{ 'true' if ( flwrap != newflwrap ) else 'false' }}"
    - debug: msg="{{ flwrap_install }}"

    - name: download flwrap and extract
      unarchive:
        src: https://sourceforge.net/projects/fldigi/files/flwrap/flwrap-{{ newflwrap }}.tar.gz
        dest: /home/pi/Downloads/
        remote_src: yes
        creates: /home/pi/Downloads/flwrap-{{newflwrap}}
      when: flwrap_install

    - name: ./configure flwrap
      command: '{{ item }} chdir=/home/pi/Downloads/flwrap-{{newflwrap}}'
      with_items:
      - ./configure
      when: flwrap_install

    - name: make flwrap 
      command: '{{ item }} chdir=/home/pi/Downloads/flwrap-{{newflwrap}}'
      with_items:
      - make
      when: flwrap_install

    - name: install flwrap
      become: yes
      command: '{{ item }} chdir=/home/pi/Downloads/flwrap-{{newflwrap}}'
      with_items:
      - make install
      when: flwrap_install

    - name: install flwrap desktop icon
      copy:
        src: flwrap.desktop
        dest: /home/pi/Desktop/flwrap.desktop
        mode: "0644"
      when: flwrap_install