---
# file: direwolf/main.yml
- name: direwolf
  hosts: localhost
  connection: localhost
  tasks:
    - name: install or update to the latest version of direwolf
      ansible.builtin.set_fact:
        direwolf_install: "{{ 'true' }}"
    - name: debug direwolf_install
      ansible.builtin.debug: msg="{{ direwolf_install }}"
    - name: install direwolf dependencies
      become: true
      ansible.builtin.apt:
        pkg:
          - build-essential
          - cmake
          - extra-xdg-menus
          - g++
          - gcc
          - git
          - libasound2-dev
          - libudev-dev
          - libusb-1.0-0-dev
          - pandoc
          - python3-numpy
          - python3-pip
        update_cache: true
        cache_valid_time: 3600
    - name: clone direwolf repo
      ansible.builtin.git:
        repo: 'https://www.github.com/wb2osz/direwolf'
        dest: "{{ ansible_env.HOME }}/Downloads/direwolf"
        version: dev
        mode: '0755'
    - name: build folder
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/Downloads/direwolf/build"
        state: directory
        mode: '0755'
    - name: cmake direwolf
      ansible.builtin.command: '{{ item }} chdir={{ ansible_env.HOME }}/Downloads/direwolf/build'
      with_items:
        - cmake ..
      when: direwolf_install
    - name: make direwolf
      ansible.builtin.command: '{{ item }} chdir={{ ansible_env.HOME }}/Downloads/direwolf/build'
      with_items:
        - make -j{{ ansible_facts['processor_count'] }}
      when: direwolf_install
    - name: make install direwolf
      become: true
      ansible.builtin.command: '{{ item }} chdir={{ ansible_env.HOME }}/Downloads/direwolf/build'
      with_items:
        - make install
      when: direwolf_install
    - name: make install-conf
      ansible.builtin.command: '{{ item }} chdir={{ ansible_env.HOME }}/Downloads/direwolf/build'
      with_items:
        - make install-conf
      when: direwolf_install
