---
# file: direwolf/main.yml
- name: direwolf
  hosts: localhost
  connection: localhost
  tasks:
    - name: Install or update to the latest version of direwolf
      ansible.builtin.set_fact:
        direwolf_install: "{{ 'true' }}"
    - name: Debug direwolf_install
      ansible.builtin.debug: 
        msg: "{{ direwolf_install }}"
    - name: Install direwolf dependencies
      become: true
      ansible.builtin.apt:
        pkg:
          - build-essential
          - cmake
          - extra-xdg-menus
          - g++
          - gcc
          - git
          - libasound2-dev
          - libudev-dev
          - libusb-1.0-0-dev
          - pandoc
          - python3-numpy
          - python3-pip
        update_cache: true
        cache_valid_time: 3600
    - name: Clone direwolf repo
      ansible.builtin.git:
        repo: 'https://www.github.com/wb2osz/direwolf'
        dest: "{{ ansible_env.HOME }}/Downloads/direwolf"
        version: dev
    - name: Build folder
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/Downloads/direwolf/build"
        state: directory
        mode: '0755'
    - name: Cmake direwolf
      ansible.builtin.command:
      args:
        chdir: "{{ ansible_env.HOME }}/Downloads/direwolf/build"
        cmd: cmake ..
        creates: "{{ ansible_env.HOME }}/Downloads/direwolf/build/src"
      when: direwolf_install
    - name: Make direwolf
      ansible.builtin.command:
      args:
        chdir: "chdir={{ ansible_env.HOME }}/Downloads/direwolf/build"
        cmd: make -j{{ ansible_facts['processor_count'] }}
        creates: "{{ ansible_env.HOME }}/Downloads/direwolf/build/src/direwolf"
      when: direwolf_install
    - name: Make install direwolf
      become: true
      ansible.builtin.command:
      args:
        chdir: "{{ ansible_env.HOME }}/Downloads/direwolf/build"
        cmd: make install
        creates: /usr/local/bin/direwolf
      when: direwolf_install
    - name: Make install-conf
      ansible.builtin.command:
      args:
        chdir: "{{ ansible_env.HOME }}/Downloads/direwolf/build"
        cmd: make install-conf
        creates: "{{ ansible_env.HOME }}/Downloads/direwolf/build/direwolf.conf"
      when: direwolf_install
