---
# file: rtl-sdr/main.yml
- name: Rtl-sdr
  hosts: localhost
  connection: localhost
  tasks:
    - name: Install or update to the latest version of rtl-sdr
      ansible.builtin.set_fact:
        rtlsdr_install: "{{ 'true' }}"
    - name: Debug rtlsdr_install
      ansible.builtin.debug:
        msg: "{{ rtlsdr_install }}"
    - name: Install rtl-sdr dependencies
      become: true
      ansible.builtin.apt:
        pkg:
          - cmake
          - build-essential
          - python3-pip
          - libusb-1.0-0-dev
          - python3-numpy
          - git
          - pandoc
      when: rtlsdr_install
    - name: Clone rtl-sdr repo
      ansible.builtin.git:
        repo: 'git://git.osmocom.org/rtl-sdr.git'
        dest: "{{ ansible_env.HOME }}/Downloads/rtl-sdr"
        version: master
    - name: Modprobe driver block
      become: true
      ansible.builtin.blockinfile:
        path: /etc/modprobe.d/no-rtl.conf
        block: |
          blacklist dvb_usb_rtl28xxu
          blacklist rtl2832
          blacklist rtl2832
        create: true
        mode: '0644'
    - name: Build folder
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/Downloads/rtl-sdr/build"
        state: directory
        mode: '0755'
    - name: Cmake rtl-sdr
      ansible.builtin.command:
      args:
        chdir: "{{ ansible_env.HOME }}/Downloads/rtl-sdr/build"
        cmd: cmake -j{{ ansible_facts['processor_count'] }}  ../ -DINSTALL_UDEV_RULES=ON
        creates: "{{ ansible_env.HOME }}/Downloads/rtl-sdr/rtlsdrConfig.cmake"
      when: rtlsdr_install
    - name: Make rtl-sdr
      ansible.builtin.command:
      args:
        chdir: "{{ ansible_env.HOME }}/Downloads/rtl-sdr/build"
        cmd: make -j{{ ansible_facts['processor_count'] }}
        creates: "{{ ansible_env.HOME }}/Downloads/rtl-sdr/build/src/rtl_test"
      when: rtlsdr_install
    - name: Install rtl-sdr
      become: true
      ansible.builtin.command:
      args:
        chdir: "{{ ansible_env.HOME }}/Downloads/rtl-sdr/build"
        cmd: make install
      changed_when: false
      when: rtlsdr_install
    - name: Ldconfig
      become: true
      ansible.builtin.command: '{{ item }} chdir={{ ansible_env.HOME }}/Downloads/rtl-sdr/build'
      with_items:
        - ldconfig
      changed_when: false
      when: rtlsdr_install
    - name: Install rtl-sdr rules
      become: true
      ansible.builtin.copy:
        src: "{{ ansible_env.HOME }}/Downloads/rtl-sdr/rtl-sdr.rules"
        dest: /etc/udev/rules.d/rtl-sdr.rules
        mode: '0644' 
      when: rtlsdr_install
