version: 2.1

workflows:
  ansible-lint-project:
    jobs:
      - build:
          context: K2EXE-RPI-context
jobs:
  build:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run: pip install ansible ansible-lint
      - run: ansible-lint --version
      - run: ansible-lint **/main.yml
      - run: ansible-lint playbook.yml
