version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run: pip install ansible ansible-lint
      - run: ansible-lint --version
      - run: ansible-lint playbook.yml
