version: 2

workflows:
  test-env-vars:
    jobs:
      - build:
          context: K2EXE-RPI-context
jobs:
  build:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run: pip install ansible ansible-lint
      - run: ansible-lint --version
      - run: ansible-lint playbook.yml
