---
# file: jnos/main.yml
- name: install and configure JNOS on raspberry pi
  hosts: localhost
  connection: localhost
  tasks:
    - name: add nosuser
      become: yes
      user:
        name: nosuser
        groups: sudo,adm
    - name: install jnos dependencies
      become: yes
      apt:
        pkg:
        - libssl-dev
        - libncurses5-dev
        - libncursesw5-dev
    - name: download and extract archive
      unarchive:
        src: https://www.langelaar.net/projects/jnos2/downloads/linux/releases/jnos2.0m.current.tar.gz
        dest: /home/nosuser/Downloads/
        remote_src: yes
        creates: /home/nosuser/Downloads/jnos2.0m.current/
    - name: ./configure jnos
      command:
        cmd: ./configure
        chdir: /home/pi/Downloads/jnos2.0m.current/rsync
        creates: /home/pi/Downloads/jnos2.0m.current/rsync/configure.okay
    - name: make jnos
      command: 
        cmd: make
        chdir: /home/pi/Downloads/jnos2.0m.current/rsync
        creates: /home/pi/Downloads/jnos2.0m.current/rsync/jnosinstaller
    - name: move installer
      copy: src={{ item.src }} dest={{ item.dest }} mode='0755'
      with_items:
        - { src: '/home/pi/Downloads/jnos2.0m.current/rsync/jnos', dest: '/home/pi/jnos2.0m.current/rsync/installerv2.1' }
        - { src: '/home/pi/Downloads/jnos2.0m.current/rsync/jnosinstaller', dest: '/home/pi/jnos2.0m.current/rsync/installerv2.1' }
### Perform custom install
#    - name: install jnos
#      become: yes
#      command:
#        cmd: /home/pi/Downloads/jnos2.0m.current/rsync/jnosinstaller
#        chdir: /home/pi/Downloads/jnos2.0m.current/rsync