---
# file: docker/main.yml
- name: docker
  hosts: localhost
  connection: localhost
  tasks:
    - name: ensure downloads folder exists
      file:
        path: /home/pi/Downloads
        state: directory
        mode: '0644'
    - name: download docker install script
      get_url: 
        url: https://get.docker.com
        dest: /home/pi/Downloads/get-docker.sh
    - name: install docker
      become: yes
      command: /home/pi/Downloads/get-docker.sh
      args:
        creates: /usr/bin/docker
        executable: /bin/sh
    - name: add pi to docker group
      become: yes
      user:
        name: pi
        group: docker
        append: yes