---
# file: docker/main.yml
- name: docker
  hosts: localhost
  connection: localhost
  tasks:
    - name: download docker install script
      shell: curl -fsSL https://get.docker.com -o get-docker.sh
      args:
        chdir: /home/pi/Downloads/
        creates: get-docker.sh
    - name: install docker
      become: yes
      shell: sh /home/pi/Downloads/get-docker.sh
      args:
        creates: /usr/bin/docker
        executable: /bin/sh
    - name: add pi to docker group
      become: yes
      user:
        name: pi
        group: docker
        append: yes