---
# file: tinc/main.yml
- name: K2EXE tinc vpn setup
  hosts: localhost
  connection: local
  tasks:
    - name: Import variables
      ansible.builtin.include_vars:
        file: vars/main.yml
    - name: Apt install tinc
      become: true
      ansible.builtin.apt:
        name: tinc
        update_cache: true
    - name: Create k2exe tinc network folder
      become: true
      ansible.builtin.file:
        path: /etc/tinc/k2exe/hosts
        state: directory
        mode: '0755'

    - name: Copy configs
      become: true
      ansible.builtin.copy: src={{ item.src }} dest={{ item.dest }} mode='0644'
      with_items:
        - { src: 'files/k2exegateway', dest: '/etc/tinc/k2exe/hosts' }

    - name: Templated tinc.conf
      become: true
      ansible.builtin.template:
        src: files/tinc.conf.j2
        dest: /etc/tinc/k2exe/tinc.conf
        owner: root
        group: root
        mode: '0644'

    - name: Templated tinc-up
      become: true
      ansible.builtin.template:
        src: files/tinc-up.j2
        dest: /etc/tinc/k2exe/tinc-up
        owner: root
        group: root
        mode: '0755'

    - name: Templated tinc-down
      become: true
      ansible.builtin.template:
        src: files/tinc-down.j2
        dest: /etc/tinc/k2exe/tinc-down
        owner: root
        group: root
        mode: '0755'

    - name: Create private key for vpn
      become: true
      ansible.builtin.command: tincd -n k2exe -K 4096
      args:
        creates: /etc/tinc/k2exe/rsa_key.priv
