---
# file: wsjtx/main.yml
- name: Wsjtx
  hosts: localhost
  connection: localhost
  tasks:
    - name: Check wsjtx installed # noqa risky-shell-pipe
      ansible.builtin.shell: |
        if hash wsjtx 2>/dev/null; then
            wsjtx_app_version -v | cut -f 2 -d' '
        else echo "NOT INSTALLED"
        fi
      register: wsjtx_installed
      changed_when: false
    - name: Set installed wsjt-x version
      ansible.builtin.set_fact:
        wsjtx: "{{ wsjtx_installed.stdout }}"
    - name: Debug wsjtx_installed
      ansible.builtin.debug:
        msg: "{{ wsjtx }}"

    - name: Latest wsjt-x version online # noqa risky-shell-pipe
      ansible.builtin.shell: |
        curl -s https://wsjt.sourceforge.io/wsjtx.html |
        grep "armhf" | grep -oP "(\d+)([.]\d+)+" | head -n 1
      register: wsjtx_online
      changed_when: false
    - name: Set latest wsjt-x version
      ansible.builtin.set_fact:
        wsjtx_32url: "https://wsjt.sourceforge.io/downloads/wsjtx_{{ wsjtx_online.stdout }}_armhf.deb"
        wsjtx_64url: "https://wsjt.sourceforge.io/downloads/wsjtx_{{ wsjtx_online.stdout }}_arm64.deb"
        wsjtx_url: {{ wsjtx_64url if ansible_facts['ansible_architecture'] == 'aarch64' else wsjtx_32url }}
    - name: Debug wsjtx_url
      ansible.builtin.debug:
        msg: "{{ wsjtx_url }}"

    - name: Set install variable
      ansible.builtin.set_fact:
        wsjtx_install: "{{ 'true' if (wsjtx != wsjtx_online) else 'false' }}"
    - name: Debug wsjtx_install
      ansible.builtin.debug:
        msg: "{{ wsjtx_install }}"

    - name: Install wsjtx dependencies
      become: true
      ansible.builtin.apt:
        pkg:
          - asciidoctor
          - autoconf
          - automake
          - build-essential
          - cmake
          - extra-xdg-menus
          - fftw3-dev
          - gfortran
          - libboost-all-dev
          - libqt5multimedia5
          - libqt5multimedia5-plugins
          - libqt5serialport5
          - libqt5printsupport5
          - libqt5sql5-sqlite
          - libtool
          - libudev-dev
          - libusb-1.0-0-dev
          - qtbase5-dev
          - qttools5-dev
          - qtmultimedia5-dev
          - texinfo
        update_cache: true
        cache_valid_time: 3600
      when: wsjtx_install

    - name: Download wsjtx deb file and install
      become: true
      ansible.builtin.apt:
        deb: "{{ wsjtx_url }}"
      when: wsjtx_install

    - name: Install wsjtx desktop icon
      ansible.builtin.copy:
        src: wsjtx.desktop
        dest: "{{ ansible_env.HOME }}/Desktop/wsjtx.desktop"
        mode: "0644"
      when: wsjtx_install
