---
# file: wsjtx/main.yml
- name: wsjtx 
  hosts: localhost
  connection: localhost
  tasks:
    - name: check wsjtx installed # noqa risky-shell-pipe
      shell: |
        if hash wsjtx 2>/dev/null; then
            wsjtx_app_version -v | cut -f 2 -d' '
        else echo "NOT INSTALLED"
        fi
      register: wsjtx_installed
      changed_when: false
    - name: set installed wsjt-x version
      set_fact: wsjtx="{{ wsjtx_installed.stdout }}"
    - name: debug wsjtx_installed
      debug: msg={{ wsjtx }}

    - name: latest wsjt-x version online # noqa risky-shell-pipe
      shell: |
        curl -s https://physics.princeton.edu/pulsar/k1jt/wsjtx.html | 
        grep "armhf" | grep -o [0-9].[0-9].[0-9] | head -n 1
      register: wsjtx_online
      args:
        warn: no
      changed_when: false
    - name: set latest wsjt-x version
      set_fact: wsjtx_url="https://physics.princeton.edu/pulsar/k1jt/wsjtx_{{ wsjtx_online.stdout }}_armhf.deb"
    - name: debug wsjtx_url
      debug: msg="{{ wsjtx_url }}"

    - name: set install variable 
      set_fact: 
        wsjtx_install: "{{ 'true' if (wsjtx != wsjtx_online) else 'false' }}"
    - name: debug wsjtx_install
      debug: msg="{{ wsjtx_install }}"

    - name: install wsjtx dependencies
      become: yes
      apt:
        pkg: 
        - libqt5multimedia5
        - libqt5multimedia5-plugins
        - libqt5serialport5
        - libqt5printsupport5
        - libqt5sql5-sqlite
        - libfftw3-single3
        - libgfortran3
        update_cache: yes
        cache_valid_time: 3600
      when: wsjtx_install

    - name: download wsjtx deb file and install
      become: yes
      apt: 
        deb: "{{ wsjtx_url }}"
      when: wsjtx_install
 
    - name: install wsjtx desktop icon
      copy:
        src: wsjtx.desktop
        dest: /home/pi/Desktop/wsjtx.desktop
        mode: "0644"
      when: wsjtx_install
