---
# file: wsjtx/main.yml
- name: wsjtx 
  hosts: localhost
  connection: localhost
  tasks:
    - name: check wsjtx installed 
      shell: |
        if hash wsjtx 2>/dev/null; then
            echo "Installed-v. unknown"
        else echo "NOT INSTALLED"
        fi
      register: wsjtx_installed
      changed_when: false
    - set_fact: wsjtx="{{ wsjtx_installed.stdout }}"
    - debug: msg={{ wsjtx }}

    - name: latest wsjtx version online
      shell: |
        curl -s https://physics.princeton.edu/pulsar/K1JT/wsjtx.html | 
        grep "<li>Version" | grep -o [0-9].[0-9].[0-9] | head -n 1
      register: wsjtx_online
      args:
        warn: no
      changed_when: false
    - set_fact: wsjtx_url="https://physics.princeton.edu/pulsar/K1JT/wsjtx_{{ wsjtx_online.stdout }}_armhf.deb"
    - debug: msg="{{ wsjtx_url }}"

    - set_fact: 
        wsjtx_install: "{{ 'true' if (wsjtx == 'NOT INSTALLED') else 'false' }}"
    - debug: msg="{{ wsjtx_install }}"

    - name: install wsjtx dependencies
      become: yes
      apt:
        pkg: 
        - libqt5multimedia5
        - libqt5multimedia5-plugins
        - libqt5serialport5
        - libqt5printsupport5
        - libqt5sql5-sqlite
        - libfftw3-single3
        - libgfortran3
      when: wsjtx_install

    - name: download wsjtx deb file and install
      become: yes
      apt: 
        deb: "{{ wsjtx_url }}"
      when: wsjtx_install
 
    - name: install wsjtx desktop icon
      copy:
        src: wsjtx.desktop
        dest: /home/pi/Desktop/wsjtx.desktop
        mode: "0644"
      when: wsjtx_install
