---
# file: nodered/main.yml
- name: Nodered
  hosts: localhost
  connection: localhost
  tasks:
    - name: Ensure downloads folder exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/Downloads"
        state: directory
        mode: '0755'
    - name: Download nodered install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered
        dest: "{{ ansible_env.HOME }}/Downloads/update-nodejs-and-nodered"
        mode: '0755'
    - name: Install nodered # noqa command-instead-of-shell (requires executable)
      ansible.builtin.shell: "{{ ansible_env.HOME }}/Downloads/update-nodejs-and-nodered --confirm-install --confirm-pi --restart"
      args:
        creates: /usr/bin/node-red
        executable: /bin/sh
      register: install_feedback
    - name: display install feedback
      ansible.builtin.debug: msg="{{ install_feedback }}"
