---
# file: piardop/main.yml
- name: piardop
  hosts: localhost
  connection: localhost
  tasks:
    - name: set piardop version
      ansible.builtin.set_fact: piardop="NOT INSTALLED" 
    - name: latest piardop version check # noqa risky-shell-pipe
      ansible.builtin.shell: |
        curl -s http://www.cantab.net/users/john.wiseman/Downloads/Beta/ | grep 'href="piardopc"' | grep -o 20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]
      register: piardop_online
      args:
        warn: false
      changed_when: false
    - name: set latest piardop version
      ansible.builtin.set_fact: newpiardop="{{ piardop_online.stdout }}" 

    - name: create piardop folder
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/piardop"
        state: directory
        mode: '0755'

    - name: download piardop to ~/piardop
      ansible.builtin.get_url:
        url: http://www.cantab.net/users/john.wiseman/Downloads/Beta/piardopc
        dest: "{{ ansible_env.HOME }}/piardop/piardopc"
        mode: '0755'

    - name: .asoundrc config
      ansible.builtin.file:
        src: .asoundrc
        dest: "{{ ansible_env.HOME }}/.asoundrc"
        state: hard
        mode: '0755'
