---
# file: tqsl/main.yml
- name: tqsl
  hosts: localhost
  connection: localhost
  tasks:
    - name: get installed tqsl version # noqa risky-shell-pipe
      ansible.builtin.shell: |
        if hash tqsl 2>/dev/null; then
            tqsl --version 2>$1 | awk 'FNR == 1 {print $3}'
        else
            echo "NOT INSTALLED"
        fi
      register: tqsl_version
      changed_when: false
    - name: debug installed tqsl version
      ansible.builtin.set_fact: tqsl="{{ tqsl_version.stdout }}"
    - name: check latest tsql version from arrl # noqa risky-shell-pipe
      ansible.builtin.shell: curl -s http://www.arrl.org/tqsl-download | grep .tar.gz | head -1 | awk -F "-" '{print $2}' | awk -F ".tar.gz" '{print $1}'
      register: tqsl_online
      args:
        warn: false
      changed_when: false
    - name: set latest tqsl version
      ansible.builtin.set_fact: newtqsl="{{ tqsl_online.stdout }}"

    - name: set_tqsl install
      ansible.builtin.set_fact:
        tqsl_install: "{{ 'true' if ( tqsl != newtqsl ) else 'false' }}"
    - name: debug tqsl_install
      ansible.builtin.debug: msg="{{ tqsl_install }}"

    - name: install tqsl dependencies
      become: true
      ansible.builtin.apt:
        pkg:
          - libdb-dev
          - libwxgtk3.0-dev
          - libcurl4-openssl-dev
        update_cache: true
        cache_valid_time: 3600
      when: tqsl_install

    - name: download tqsl and extract
      ansible.builtin.unarchive:
        src: http://www.arrl.org/tqsl/tqsl-{{ newtqsl }}.tar.gz
        dest: "{{ ansible_env.HOME }}/Downloads/"
        remote_src: true
        creates: "{{ ansible_env.HOME }}/Downloads/tqsl-{{ newtqsl }}"
      when: tqsl_install

    - name: cmake tqsl
      ansible.builtin.command: '{{ item }} chdir={{ ansible_env.HOME }}/Downloads/tqsl-{{ newtqsl }}'
      with_items:
        - cmake .
      when: tqsl_install

    - name: make tqsl
      ansible.builtin.command: '{{ item }} chdir={{ ansible_env.HOME }}/Downloads/tqsl-{{ newtqsl }}'
      with_items:
        - make
      when: tqsl_install

    - name: install tqsl
      become: true
      ansible.builtin.command: '{{ item }} chdir={{ ansible_env.HOME }}/Downloads/tqsl-{{ newtqsl }}'
      with_items:
        - make install
      when: tqsl_install
