---
# file: pat/main.yml
- name: Install pat
  hosts: localhost
  connection: localhost
  tasks:
    - name: Check installed pat version # noqa risky-shell-pipe
      ansible.builtin.shell: |
        if hash pat 2>/dev/null; then
          pat version | awk -F 'v' '{print $2}' | head -c 5
        else echo "NOT INSTALLED"
        fi
      register: pat_version
      changed_when: false
    - name: Set installed pat version
      ansible.builtin.set_fact:
        pat: "{{ pat_version.stdout }}"

    - name: Check latest pat version # noqa risky-shell-pipe
      ansible.builtin.shell: |
        curl -s https://github.com/la5nta/pat/releases | grep -m 1 "amd64.deb" |
        awk -F '_' '{print $2}'
      register: pat_online
      changed_when: false
    - name: Set latest pat version
      ansible.builtin.set_fact:
        newpat: "{{ pat_online.stdout }}"

    - name: Install or update pat
      ansible.builtin.set_fact:
        pat_install: "{{ 'true' if (pat != newpat) else 'false' }}"
    - name: Debug pat_install
      ansible.builtin.debug:
        msg: "{{ pat_install }}"
    - name: Dpkg architecture
      ansible.builtin.command:
      args:
        cmd: dpkg --package-architecture
        register: arch
    - name: Download pat deb file and install
      become: true
      ansible.builtin.apt:
        deb: https://github.com/la5nta/pat/releases/download/v{{ newpat }}/pat_{{ newpat }}_linux_{{ arch.stdout }}.deb
      when: pat_install
