---
# file: pat/main.yml
- name: install pat
  hosts: localhost
  connection: localhost
  tasks:
    - name: check installed pat version
      shell: |
        if hash pat 2>/dev/null; then
          pat version | awk -F 'v' '{print $2}' | head -c 5
        else echo "NOT INSTALLED"
        fi
      register: pat_version
      changed_when: false
    - set_fact: pat="{{ pat_version.stdout }}"

    - name: check latest pat version
      shell: |
        curl -s https://github.com/la5nta/pat/releases | grep -m 1 "amd64.deb" |
        awk -F '_' '{print $2}'
      register: pat_online
      args:
        warn: no
      changed_when: false
    - set_fact: newpat="{{ pat_online.stdout }}"

    - name: install or update pat 
      set_fact:
        pat_install: "{{ 'true' if (pat != newpat) else 'false' }}"
    - debug: msg="{{ pat_install }}"

    - name: download pat deb file and install
      become: yes
      apt:
        deb: https://github.com/la5nta/pat/releases/download/v{{newpat}}/pat_{{newpat}}_linux_armhf.deb
      when: pat_install