---
# file: flmsg/main.yml
- name: Flmsg
  hosts: localhost
  connection: localhost
  tasks:
    - name: Get installed flmsg version # noqa risky-shell-pipe
      ansible.builtin.shell: |
        if hash flmsg 2>/dev/null; then
            flmsg --version | awk 'FNR == 1 {print $2}'
        else
            echo "NOT INSTALLED"
        fi
      register: flmsg_version
      changed_when: false
    - name: Debug installed flidigi version
      ansible.builtin.set_fact: 
        flmsg: "{{ flmsg_version.stdout }}"

    - name: Check latest flmsg version from sourceforge # noqa risky-shell-pipe
      ansible.builtin.shell: |
        curl -s https://sourceforge.net/projects/fldigi/files/flmsg/ | grep .tar.gz | head -1 | awk -F "-" '{print $2}' | awk -F ".tar.gz" '{print $1}'
      register: flmsg_online
      changed_when: false
    - name: Debug latest fldigi version
      ansible.builtin.set_fact: 
        newflmsg: "{{  flmsg_online.stdout }}"

    - name: Install or update to the latest version of flmsg
      ansible.builtin.set_fact:
        flmsg_install: "{{ 'true' if (flmsg != newflmsg) else 'false' }}"
    - name: Debug flmsg_install
      ansible.builtin.debug: 
        msg: "{{ flmsg_install }}"

    - name: Download flmsg and extract
      ansible.builtin.unarchive:
        src: https://sourceforge.net/projects/fldigi/files/flmsg/flmsg-{{ newflmsg }}.tar.gz
        dest: "{{ ansible_env.HOME }}/Downloads/"
        remote_src: true
        creates: "{{ ansible_env.HOME }}/Downloads/flmsg-{{ newflmsg }}"
      when: flmsg_install

    - name: ./configure flmsg
      ansible.builtin.command:
      argv:
        chdir: "{{ ansible_env.HOME }}/Downloads/flmsg-{{ newflmsg }}"
        cmd: ./configure
        creates: "{{ ansible_env.HOME }}/Downloads/flmsg-{{ newflmsg }}/config.status"
      when: flmsg_install

    - name: Make flmsg
      ansible.builtin.command:
      argv:
        chdir: "{{ ansible_env.HOME }}/Downloads/flmsg-{{ newflmsg }}"
        cmd: make -j{{ ansible_facts['processor_count'] }}
        creates: "{{ ansible_env.HOME }}/Downloads/flmsg-{{ newflmsg }}/src/flmsg" 
      when: flmsg_install

    - name: Install flmsg
      become: true
      ansible.builtin.command:
      argv:
        chdir: "{{ ansible_env.HOME }}/Downloads/flmsg-{{ newflmsg }}"
        cmd: make install
        creates: /usr/bin/local/flmsg
      when: flmsg_install

    - name: Install flmsg desktop icon
      ansible.builtin.copy:
        src: flmsg.desktop
        dest: "{{ ansible_env.HOME }}/Desktop/flmsg.desktop"
        mode: "0644"
      when: flmsg_install
